// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhW8ub-MJPnPZDERrFLiGhK2SrbXW0U0',
    appId: '1:355200257738:web:43e2b65636d247506dee33',
    messagingSenderId: '355200257738',
    projectId: 'heartland-161d6',
    authDomain: 'heartland-161d6.firebaseapp.com',
    storageBucket: 'heartland-161d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1QGUkTOfsMqVVcSDvw8LfSI8Jqzkos8',
    appId: '1:355200257738:android:24797d29bb8921236dee33',
    messagingSenderId: '355200257738',
    projectId: 'heartland-161d6',
    storageBucket: 'heartland-161d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHEHqyPx5hGR4MJZMGZDE4pRacs7t953Y',
    appId: '1:355200257738:ios:4fb547c1e25b89566dee33',
    messagingSenderId: '355200257738',
    projectId: 'heartland-161d6',
    storageBucket: 'heartland-161d6.appspot.com',
    iosBundleId: 'com.example.heartlandPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHEHqyPx5hGR4MJZMGZDE4pRacs7t953Y',
    appId: '1:355200257738:ios:4fb547c1e25b89566dee33',
    messagingSenderId: '355200257738',
    projectId: 'heartland-161d6',
    storageBucket: 'heartland-161d6.appspot.com',
    iosBundleId: 'com.example.heartlandPhotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhW8ub-MJPnPZDERrFLiGhK2SrbXW0U0',
    appId: '1:355200257738:web:abe17244199947eb6dee33',
    messagingSenderId: '355200257738',
    projectId: 'heartland-161d6',
    authDomain: 'heartland-161d6.firebaseapp.com',
    storageBucket: 'heartland-161d6.appspot.com',
  );
}
